apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: muhammadbilal146/client:f6eb5573f15121acfd9171ab7f27379225d0b28b
          ports:
            - containerPort: 80