apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: muhammadbilal146/posts:f6eb5573f15121acfd9171ab7f27379225d0b28b
          ports:
            - containerPort: 8001